-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.alerts (
  id integer NOT NULL DEFAULT nextval('alerts_id_seq'::regclass),
  organization_id integer NOT NULL,
  donor_id integer,
  donation_id integer,
  compliance_case_id integer,
  alert_type text NOT NULL CHECK (alert_type = ANY (ARRAY['cash_detected'::text, 'incomplete_info'::text, 'notice_overdue'::text, 'risk_evaluation_pending'::text, 'reputation_flag'::text, 'threshold_identification'::text, 'threshold_notice'::text, 'document_expired'::text, 'aviso_deadline_approaching'::text])),
  severity text DEFAULT 'medium'::text CHECK (severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  title text NOT NULL,
  description text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'acknowledged'::text, 'resolved'::text, 'dismissed'::text])),
  acknowledged_by text,
  acknowledged_date timestamp without time zone,
  resolved_date timestamp without time zone,
  auto_generated boolean DEFAULT true,
  CONSTRAINT alerts_pkey PRIMARY KEY (id),
  CONSTRAINT alerts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT alerts_donor_id_fkey FOREIGN KEY (donor_id) REFERENCES public.donors(id),
  CONSTRAINT alerts_donation_id_fkey FOREIGN KEY (donation_id) REFERENCES public.donations(id),
  CONSTRAINT alerts_compliance_case_id_fkey FOREIGN KEY (compliance_case_id) REFERENCES public.compliance_cases(id)
);
CREATE TABLE public.audit_logs (
  id integer NOT NULL DEFAULT nextval('audit_logs_id_seq'::regclass),
  organization_id integer,
  user_email text,
  user_role text,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id text,
  description text,
  ip_address text,
  metadata jsonb,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.compliance_cases (
  id integer NOT NULL DEFAULT nextval('compliance_cases_id_seq'::regclass),
  organization_id integer NOT NULL,
  donor_id integer NOT NULL,
  case_type text DEFAULT 'aviso_sat'::text CHECK (case_type = ANY (ARRAY['identification'::text, 'aviso_sat'::text])),
  threshold_triggered text CHECK (threshold_triggered = ANY (ARRAY['identification'::text, 'notice'::text])),
  threshold_uma numeric,
  accumulated_mxn numeric,
  accumulated_uma numeric,
  trigger_date date NOT NULL,
  deadline_date date,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in_preparation'::text, 'captured_sat'::text, 'presented'::text, 'closed'::text, 'overdue'::text])),
  sat_folio text,
  evidence_url text,
  presented_date date,
  notes text,
  assigned_to text,
  appleseed_notes text,
  risk_evaluation_done boolean DEFAULT false,
  template_generated boolean DEFAULT false,
  CONSTRAINT compliance_cases_pkey PRIMARY KEY (id),
  CONSTRAINT compliance_cases_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT compliance_cases_donor_id_fkey FOREIGN KEY (donor_id) REFERENCES public.donors(id)
);
CREATE TABLE public.donations (
  id integer NOT NULL DEFAULT nextval('donations_id_seq'::regclass),
  organization_id integer NOT NULL,
  donor_id integer NOT NULL,
  amount_mxn numeric NOT NULL,
  amount_uma numeric,
  donation_date date NOT NULL,
  payment_method text NOT NULL CHECK (payment_method = ANY (ARRAY['transferencia'::text, 'cheque'::text, 'tarjeta'::text, 'efectivo'::text, 'otro'::text])),
  description text,
  reference text,
  receipt_url text,
  accumulated_6m_at_donation numeric,
  accumulated_uma_6m numeric,
  threshold_triggered text DEFAULT 'none'::text CHECK (threshold_triggered = ANY (ARRAY['none'::text, 'identification'::text, 'notice'::text])),
  is_manual_entry boolean DEFAULT false,
  entry_notes text,
  status text DEFAULT 'registered'::text CHECK (status = ANY (ARRAY['registered'::text, 'blocked'::text, 'cancelled'::text])),
  compliance_case_id integer,
  CONSTRAINT donations_pkey PRIMARY KEY (id),
  CONSTRAINT donations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT donations_donor_id_fkey FOREIGN KEY (donor_id) REFERENCES public.donors(id),
  CONSTRAINT donations_compliance_case_id_fkey FOREIGN KEY (compliance_case_id) REFERENCES public.compliance_cases(id)
);
CREATE TABLE public.donor_documents (
  id integer NOT NULL DEFAULT nextval('donor_documents_id_seq'::regclass),
  donor_id integer NOT NULL,
  organization_id integer NOT NULL,
  document_type text NOT NULL CHECK (document_type = ANY (ARRAY['acta_constitutiva'::text, 'comprobante_domicilio'::text, 'poder_representante'::text, 'identificacion_representante'::text, 'cedula_fiscal'::text, 'constancia_dueno_beneficiario'::text, 'identificacion_dueno_beneficiario'::text, 'otro'::text])),
  document_name text,
  file_url text,
  upload_date date,
  expiry_date date,
  is_verified boolean DEFAULT false,
  verified_by text,
  verified_date date,
  notes text,
  version integer DEFAULT 1,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'valid'::text, 'expired'::text, 'rejected'::text])),
  CONSTRAINT donor_documents_pkey PRIMARY KEY (id),
  CONSTRAINT donor_documents_donor_id_fkey FOREIGN KEY (donor_id) REFERENCES public.donors(id),
  CONSTRAINT donor_documents_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.donors (
  id integer NOT NULL DEFAULT nextval('donors_id_seq'::regclass),
  organization_id integer NOT NULL,
  donor_type text DEFAULT 'fisica'::text CHECK (donor_type = ANY (ARRAY['fisica'::text, 'moral'::text])),
  full_name text NOT NULL,
  rfc text,
  curp text,
  birth_date date,
  nationality text DEFAULT 'Mexicana'::text,
  country_of_incorporation text,
  incorporation_date date,
  activity text,
  address text,
  city text,
  state text,
  zip_code text,
  country text DEFAULT 'México'::text,
  phone text,
  email text,
  legal_rep_name text,
  legal_rep_rfc text,
  legal_rep_curp text,
  legal_rep_birth_date date,
  legal_rep_id_authority text,
  legal_rep_id_number text,
  beneficial_owner_exists boolean DEFAULT false,
  beneficial_owner_name text,
  beneficial_owner_rfc text,
  pep_flag boolean DEFAULT false,
  reputation_flag boolean DEFAULT false,
  reputation_notes text,
  risk_level text DEFAULT 'low'::text CHECK (risk_level = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  compliance_status text DEFAULT 'incomplete'::text CHECK (compliance_status = ANY (ARRAY['ok'::text, 'identification_required'::text, 'notice_required'::text, 'blocked'::text, 'incomplete'::text])),
  kyc_complete boolean DEFAULT false,
  portal_user_email text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['active'::text, 'blocked'::text, 'pending'::text])),
  CONSTRAINT donors_pkey PRIMARY KEY (id),
  CONSTRAINT donors_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.organizations (
  id integer NOT NULL DEFAULT nextval('organizations_id_seq'::regclass),
  name text NOT NULL,
  rfc text NOT NULL,
  moral_type text CHECK (moral_type = ANY (ARRAY['Asociación Civil'::text, 'Sociedad Civil'::text, 'Fundación'::text, 'Instituto'::text, 'Otro'::text])),
  address text,
  city text,
  state text,
  zip_code text,
  phone text,
  email text,
  legal_rep_name text,
  legal_rep_rfc text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'suspended'::text])),
  plan text DEFAULT 'trial'::text CHECK (plan = ANY (ARRAY['trial'::text, 'basic'::text, 'professional'::text, 'enterprise'::text])),
  logo_url text,
  uma_config_id integer,
  risk_profile text DEFAULT 'low'::text CHECK (risk_profile = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])),
  notes text,
  CONSTRAINT organizations_pkey PRIMARY KEY (id),
  CONSTRAINT organizations_uma_config_id_fkey FOREIGN KEY (uma_config_id) REFERENCES public.uma_config(id)
);
CREATE TABLE public.support_tickets (
  id integer NOT NULL DEFAULT nextval('support_tickets_id_seq'::regclass),
  organization_id integer,
  compliance_case_id integer,
  donor_id integer,
  title text NOT NULL,
  description text NOT NULL,
  category text DEFAULT 'compliance'::text CHECK (category = ANY (ARRAY['compliance'::text, 'technical'::text, 'billing'::text, 'general'::text])),
  priority text DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  status text DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'in_progress'::text, 'pending_osc'::text, 'resolved'::text, 'closed'::text])),
  assigned_to text,
  notes jsonb,
  resolved_date timestamp without time zone,
  CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT support_tickets_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT support_tickets_compliance_case_id_fkey FOREIGN KEY (compliance_case_id) REFERENCES public.compliance_cases(id),
  CONSTRAINT support_tickets_donor_id_fkey FOREIGN KEY (donor_id) REFERENCES public.donors(id)
);
CREATE TABLE public.uma_config (
  id integer NOT NULL DEFAULT nextval('uma_config_id_seq'::regclass),
  year integer NOT NULL,
  daily_value_mxn numeric NOT NULL,
  annual_value_mxn numeric,
  threshold_identification_uma integer DEFAULT 1605,
  threshold_notice_uma integer DEFAULT 3210,
  is_active boolean DEFAULT true,
  source text,
  notes text,
  CONSTRAINT uma_config_pkey PRIMARY KEY (id)
);